[package]
name = "non-empty-vec"
description = "`NonEmpty` vector implementation, ensure non-emptiness by construction."
version = "0.1.2"
authors = ["yihuang <yi.codeplayer@gmail.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/yihuang/non-empty-vec"

[dependencies]
